on:
  push:
    paths:
      - "DC-*"
      - "adoc/**"
      - ".github/workflows/*"
  pull_request:
    paths:
      - "DC-*"
      - "adoc/**"
  workflow_dispatch:


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openSUSE/doc-ci@gha-validate
        with:
          dc-files: "DC-release-notes-micro DC-release-notes-micro-60 DC-release-notes-micro-61 DC-release-notes-sles-160"
          validate-ids: true
          validate-images: true
          validate-tables: true
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: openSUSE/doc-ci@gha-build
        id: build-dc
        with:
          dc-files: "DC-release-notes-micro DC-release-notes-micro-60 DC-release-notes-micro-61 DC-release-notes-sles-160"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-dc.outputs.artifact-name }}
          path: ${{ steps.build-dc.outputs.artifact-dir }}/*
          retention-days: 3
  publish:
    runs-on: ubuntu-latest
    if: ${{ success() }} && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    continue-on-error: true
    steps:
      - name: Downloading all build artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact-dir
      - name: Create folder hierarchy for susedoc.github.io
        run: |
          mkdir -p publish/release-notes-micro{-60-all,-60,-61}/html
          mkdir -p publish/release-notes-sles-160/html
          OUTPUT_DIR=$(find artifact-dir -mindepth 1 -maxdepth 1 -type d)
          mv "$OUTPUT_DIR/html/release-notes-micro" publish/release-notes-micro-60-all/html
          mv "$OUTPUT_DIR/html/release-notes-micro-60" publish/release-notes-micro-60/html
          mv "$OUTPUT_DIR/html/release-notes-micro-61" publish/release-notes-micro-61/html
          mv "$OUTPUT_DIR/html/release-notes-sles-160" publish/release-notes-sles-160/html
          rm -rf artifact-dir
          mv publish artifact-dir
      - name: Publishing builds on susedoc.github.io
        uses: SUSE/release-notes@gha-publish
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          artifact-path:  artifact-dir
          publish-repo: gh:SUSEdoc/release-notes.git
          repo-reset-after: 35